on:
  push:
    branches:
      - main

name: Deploy website on push

jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Get latest code
      uses: actions/checkout@v3

    - name: Add UTF-8 BOM to relevant files
      run: |
        for file in index.html lz.js lz.css; do
          if [ -f "$file" ]; then
            bom=$(head -c 3 "$file" | xxd -p)
            if [ "$bom" != "efbbbf" ]; then
              echo "Adding BOM to: $file"
              mv "$file" "$file.bak"
              (echo -ne '\xEF\xBB\xBF'; cat "$file.bak") > "$file"
              rm "$file.bak"
            fi
          fi
        done

    - name: Push files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: lz.free.bg
        username: lz.free.bg
        password: ${{ secrets.ftp_password }}
        state-name: ftp-deploy-sync-state.json
